# -*- coding: utf-8 -*-
"""sms spam detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_sgexb04k2S7IkYCc6pV8O82tH4MUCW

load dataset
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

print("Path to dataset files:", path)

import pandas as pd

df = pd.read_csv(path + "/spam.csv", encoding="latin-1")
df.head()

"""Eda

"""

df = df.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)
df = df.rename(columns={"v1": "label", "v2": "text"})
df.head()

df.isna().sum()

df.info()

df.shape

df['label'].value_counts()

df = pd.DataFrame(df)
df.head()

"""clean text

"""

df['text']=df['text'].str.lower()
df.head()

df = df.drop_duplicates(keep='first')

import re
def clean_text (text) :
  text = re.sub(r'[^a-zA-Z]', ' ', text)
  return text
df['text']=df['text'].apply(clean_text)
df['text'].head()

df['text'] = df['text'].str.split().str.join(' ')
df.head()

import nltk
nltk.download('stopwords')

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range=(1,2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True)
x = vectorizer.fit_transform(df['text']).toarray()
y = df['label']
x.shape

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
model = MultinomialNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = classification_report(y_test, y_pred)
print(accuracy)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(class_weight="balanced")
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = classification_report(y_test, y_pred)
print( accuracy)

from sklearn.svm import SVC
model = SVC(    kernel="linear",     class_weight="balanced")
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = classification_report(y_test, y_pred)
print(accuracy)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer2 = TfidfVectorizer(max_features=5000,ngram_range=(1,2),stop_words="english")
x2 = vectorizer2.fit_transform(df['text']).toarray()
y2 = df['label']
x2.shape

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x2,y,test_size=0.2,random_state=42)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
model = MultinomialNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = classification_report(y_test, y_pred)
print( accuracy)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = classification_report(y_test, y_pred)
print( accuracy)

from sklearn.svm import SVC
model = SVC()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = classification_report(y_test, y_pred)
print( accuracy)